**Adit Punamiya**

I003

Btech AI Sem 4

**Lab 4 Part B**

In [34]:
import pandas as pd
import numpy as np

In [35]:
data=pd.read_csv("Admission.csv")

In [36]:
data.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA   
0           1        337          118                  4  4.5   4.5  9.65  \
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [37]:
data.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA   
0           1        337          118                  4  4.5   4.5  9.65  \
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [38]:
data.size

3600

In [39]:
data.shape

(400, 9)

In [40]:
data.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Serial No.         400 non-null    int64  
 1   GRE Score          400 non-null    int64  
 2   TOEFL Score        400 non-null    int64  
 3   University Rating  400 non-null    int64  
 4   SOP                400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64  
 8   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 28.2 KB


In [42]:
data.drop(["Serial No."],axis=1,inplace=True) #axis=1 drops column, else axis=0 drops rows

In [43]:
data.head(5)

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research   
0        337          118                  4  4.5   4.5  9.65         1  \
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65

In [44]:
X=data.drop(columns=["Chance of Admit "])
y=data["Chance of Admit "]

In [45]:
X.head(5)

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0        337          118                  4  4.5   4.5  9.65         1
1        324          107                  4  4.0   4.5  8.87         1
2        316          104                  3  3.0   3.5  8.00         1
3        322          110                  3  3.5   2.5  8.67         1
4        314          103                  2  2.0   3.0  8.21         0

In [46]:
y.head(5)

0    0.92
1    0.76
2    0.72
3    0.80
4    0.65
Name: Chance of Admit , dtype: float64

In [47]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(X)
X=scalar.transform(X)

In [48]:
X[:5]

array([[ 1.76210664,  1.74697064,  0.79882862,  1.09386422,  1.16732114,
         1.76481828,  0.90911166],
       [ 0.62765641, -0.06763531,  0.79882862,  0.59665321,  1.16732114,
         0.45515126,  0.90911166],
       [-0.07046681, -0.56252785, -0.07660001, -0.39776881,  0.05293342,
        -1.00563118,  0.90911166],
       [ 0.4531256 ,  0.42725722, -0.07660001,  0.0994422 , -1.06145431,
         0.11933921,  0.90911166],
       [-0.24499762, -0.72749202, -0.95202863, -1.39219083, -0.50426044,
        -0.65302852, -1.09997489]])

In [49]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42) #random state is the same as random seed
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((320, 7), (80, 7), (320,), (80,))

In [50]:
from sklearn.linear_model import LinearRegression
lr_model=LinearRegression()
lr_model.fit(X_train,y_train)

LinearRegression()

In [51]:
lr_model.coef_

array([ 0.02134305,  0.01651078,  0.00842724, -0.00029438,  0.01415149,
        0.06829365,  0.01106326])

In [52]:
test_values=np.array([[337,118,4,4.5,4.5,9.65,1]])
test_values_scaled=scalar.transform(test_values)

c:\Users\Adit Punamiya\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [53]:
lr_model.predict(test_values_scaled)

array([0.94677007])

In [54]:
y_pred=lr_model.predict(X_test)

In [55]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.8212082591486991

In [56]:
import pickle

In [57]:
#Save the model
pickle_out=open("lr_model.pkl","wb") #wb -> write in binary
pickle.dump(lr_model,pickle_out) #writing the file in binary format
pickle_out.close()

In [58]:
pickle_out=open("scalar.pkl","wb")
pickle.dump(scalar,pickle_out)
pickle_out.close()

**Conclusion:** Using Linear Regression to predict the chance of getting admitted to college using  a dataset containing information about students' grades, SAT scores, and other relevant factors can help in making accurate predictions and converting the parameters to a binary file to apply that in a web app that is made using StreamLit.